# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Run PR Title Printer'
Rake::Task.define_task(:run_pr_title_printer) do
  puts 'Provide the branch name you would like to generate a PR title for'
  branch_name = $stdin.gets&.chomp&.strip

  params = { branch_name: }.reject { |_, value| value&.empty? }

  puts Application.run(**params)
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
